import Header from '@/src/components/Header'
import Footer from '@/src/components/Footer'

export default function Features() {
  const features = [
    {
      title: 'Automated Alumni Research',
      description: 'Submit a simple spreadsheet of student and alumni names. Our platform conducts comprehensive online research on each individual to build detailed professional profiles.',
      icon: '🔍',
    },
    {
      title: 'Entrepreneurship Tracking',
      description: 'Identify and track companies founded by your alumni. Get data on founding dates, funding raised, current status, and company growth metrics.',
      icon: '🚀',
    },
    {
      title: 'Career Progression Analytics',
      description: 'Track promotions, role changes, and advancement patterns across your alumni network. Understand career trajectories and identify success patterns.',
      icon: '📈',
    },
    {
      title: 'Economic Impact Measurement',
      description: 'Quantify the economic impact of your institution through metrics like jobs created, venture capital raised, and revenue generated by alumni-founded companies.',
      icon: '💰',
    },
    {
      title: 'Exit Event Identification',
      description: 'Track significant career milestones including mergers, acquisitions, IPOs, and other major business events involving your alumni.',
      icon: '🎯',
    },
    {
      title: 'Aggregated Reporting',
      description: 'Receive comprehensive reports that aggregate individual achievements into cohort-level insights and trend analysis for board presentations and strategic planning.',
      icon: '📊',
    },
  ]

  return (
    <main className="min-h-screen flex flex-col">
      <Header />
      <div className="flex-1">
        <div className="bg-gradient-to-r from-blue-600 to-blue-800 text-white py-20 px-4">
          <div className="max-w-4xl mx-auto">
            <h1 className="text-5xl font-bold mb-6">Our Features</h1>
            <p className="text-xl opacity-90">Comprehensive tools to measure and demonstrate educational impact</p>
          </div>
        </div>

        <div className="max-w-6xl mx-auto py-20 px-4">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="bg-white border border-gray-200 rounded-lg p-8 hover:shadow-lg transition-shadow">
                <div className="text-4xl mb-4">{feature.icon}</div>
                <h3 className="text-xl font-bold mb-3 text-gray-900">{feature.title}</h3>
                <p className="text-gray-700 leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
      <Footer />
    </main>
  )
}
