import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Link from 'next/link';

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen bg-white">
      <Header />
      
      {/* Hero Section */}
      <section className="bg-gradient-to-r from-blue-600 to-blue-800 text-white py-20 px-4 md:px-8">
        <div className="max-w-6xl mx-auto">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">Measure the Real Impact of Your Education</h1>
          <p className="text-lg md:text-xl mb-8 text-blue-100 max-w-2xl">Track where your alumni succeed. Understand the full scope of your institution's influence on careers, companies, and communities.</p>
          <button className="bg-white text-blue-700 px-8 py-3 rounded-lg font-semibold hover:bg-blue-50 transition">
            Get Started Today
          </button>
        </div>
      </section>

      {/* Key Metrics Section */}
      <section className="py-16 px-4 md:px-8 bg-gray-50">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-900 mb-12 text-center">What We Track</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {[
              { icon: '🚀', title: 'Companies Started', desc: 'Entrepreneurship and startup founding' },
              { icon: '📈', title: 'Promotions & Roles', desc: 'Career advancement and leadership positions' },
              { icon: '👥', title: 'Jobs Created', desc: 'Employment generated by alumni' },
              { icon: '💰', title: 'Venture Capital', desc: 'Funding raised by alumni ventures' },
              { icon: 'M&A', title: 'Acquisitions', desc: 'Mergers and acquisition activity' },
              { icon: '🎯', title: 'Exit Events', desc: 'IPOs and successful exits' },
              { icon: '🏆', title: 'Awards & Recognition', desc: 'Industry recognition and honors' },
              { icon: '🌍', title: 'Global Impact', desc: 'Influence across industries and sectors' }
            ].map((item, idx) => (
              <div key={idx} className="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition">
                <div className="text-4xl mb-4">{item.icon}</div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">{item.title}</h3>
                <p className="text-gray-600 text-sm">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-16 px-4 md:px-8">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-900 mb-12 text-center">How It Works</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                step: '1',
                title: 'Submit Your Data',
                desc: 'Upload a spreadsheet of student and alumni names. We accept various formats and handle data securely.'
              },
              {
                step: '2',
                title: 'Our Research Team Acts',
                desc: 'We conduct comprehensive online research for each individual, tracking career progression, companies, funding, and achievements.'
              },
              {
                step: '3',
                title: 'Get Detailed Insights',
                desc: 'Receive aggregated reports and analytics demonstrating your institution\'s impact on alumni success and societal contribution.'
              }
            ].map((item, idx) => (
              <div key={idx} className="relative">
                <div className="flex items-start">
                  <div className="flex-shrink-0">
                    <div className="flex items-center justify-center h-12 w-12 rounded-md bg-blue-600 text-white font-bold text-lg">
                      {item.step}
                    </div>
                  </div>
                  <div className="ml-4">
                    <h3 className="text-xl font-semibold text-gray-900">{item.title}</h3>
                    <p className="mt-2 text-gray-600">{item.desc}</p>
                  </div>
                </div>
                {idx < 2 && (
                  <div className="hidden md:block absolute top-6 left-24 w-24 h-0.5 bg-gray-300"></div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-blue-700 text-white py-16 px-4 md:px-8">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to Demonstrate Your Impact?</h2>
          <p className="text-lg mb-8 text-blue-100">Join leading universities and educational institutions in leveraging alumni data to showcase institutional excellence.</p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button className="bg-white text-blue-700 px-8 py-3 rounded-lg font-semibold hover:bg-blue-50 transition">
              Schedule a Demo
            </button>
            <Link href="/about" className="bg-blue-600 border-2 border-white text-white px-8 py-3 rounded-lg font-semibold hover:bg-blue-800 transition">
              Learn About Our Team
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}