import Header from '@/components/Header';
import Footer from '@/components/Footer';
import CTA from '@/components/CTA';

function Hero() {
  return (
    <section className="bg-gradient-to-br from-yellow-50 to-amber-50 py-20 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <div>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-gray-900 mb-6 leading-tight">
              Measure Your Institution's Real-World Impact
            </h1>
            <p className="text-lg sm:text-xl text-gray-700 mb-8 leading-relaxed">
              Transform alumni spreadsheets into powerful impact metrics. We conduct comprehensive research on each graduate to identify companies founded, capital raised, jobs created, and transformative exit events. Demonstrate the true value of your education and research to donors, policymakers, and stakeholders.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <button className="bg-yellow-500 text-gray-900 px-8 py-3 rounded-lg hover:bg-yellow-600 transition font-semibold">
                Get Started
              </button>
              <button className="border-2 border-yellow-500 text-yellow-600 px-8 py-3 rounded-lg hover:bg-yellow-50 transition font-semibold">
                Schedule Demo
              </button>
            </div>
          </div>
          <div className="bg-white rounded-2xl shadow-lg p-8 border border-gray-100">
            <div className="space-y-6">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 bg-yellow-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <span className="text-2xl">1</span>
                </div>
                <div>
                  <p className="font-semibold text-gray-900">Upload Alumni Names</p>
                  <p className="text-sm text-gray-600">Simple spreadsheet with student/alumni data</p>
                </div>
              </div>
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 bg-yellow-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <span className="text-2xl">2</span>
                </div>
                <div>
                  <p className="font-semibold text-gray-900">Comprehensive Research</p>
                  <p className="text-sm text-gray-600">We track each person's professional journey online</p>
                </div>
              </div>
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 bg-yellow-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <span className="text-2xl">3</span>
                </div>
                <div>
                  <p className="font-semibold text-gray-900">Aggregate Impact Metrics</p>
                  <p className="text-sm text-gray-600">Companies, capital, jobs, promotions, and exits</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function Features() {
  const features = [
    {
      icon: '10',
      title: 'Companies Founded',
      description: 'Identify and quantify startups and ventures launched by your alumni across all industries.',
    },
    {
      icon: '20',
      title: 'Venture Capital Raised',
      description: 'Track the total funding secured by alumni-led companies from seed to growth stage.',
    },
    {
      icon: '30',
      title: 'Jobs Created',
      description: 'Aggregate the employment opportunities generated by your entrepreneurial alumni.',
    },
    {
      icon: '40',
      title: 'Career Advancement',
      description: 'Document promotions, leadership positions, and career progression across industries.',
    },
    {
      icon: '50',
      title: 'Exit Events',
      description: 'Capture IPOs, acquisitions, and mergers involving your alumni as founders or executives.',
    },
    {
      icon: '60',
      title: 'Custom Analytics',
      description: 'Segment results by graduation year, field of study, or demographics for deeper insights.',
    },
  ];

  return (
    <section id="features" className="py-20 px-4 sm:px-6 lg:px-8 bg-white">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-gray-900 mb-4">
            Measure What Matters
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Track the real-world impact of your institution through alumni professional achievements and outcomes.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <div
              key={index}
              className="bg-gray-50 rounded-xl p-8 hover:shadow-lg hover:bg-yellow-50 transition duration-300 border border-gray-100"
            >
              <div className="text-4xl font-bold text-yellow-500 mb-4">{feature.icon}</div>
              <h3 className="text-xl font-bold text-gray-900 mb-3">{feature.title}</h3>
              <p className="text-gray-600 leading-relaxed">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function Process() {
  const steps = [
    {
      number: '1',
      title: 'Submit Alumni Names',
      description: 'Provide a spreadsheet with student and alumni names in CSV, Excel, or other common formats.',
    },
    {
      number: '2',
      title: 'Vast Online Research',
      description: 'Our team conducts comprehensive research on each individual across online sources and databases.',
    },
    {
      number: '3',
      title: 'Aggregate Results',
      description: 'We compile professional achievements into meaningful metrics and impact narratives.',
    },
    {
      number: '4',
      title: 'Get Your Report',
      description: 'Receive detailed dashboards and reports demonstrating your institution\'s alumni impact.',
    },
  ];

  return (
    <section className="py-20 px-4 sm:px-6 lg:px-8 bg-gray-50">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-gray-900 mb-4">
            Simple, Proven Process
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            From data upload to impact report in four straightforward steps.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {steps.map((step, index) => (
            <div key={index} className="relative">
              {index < steps.length - 1 && (
                <div className="hidden lg:block absolute top-16 left-full w-full h-0.5 bg-yellow-300 -z-10"></div>
              )}

              <div className="bg-white rounded-xl p-6 border border-gray-200 h-full">
                <div className="w-12 h-12 bg-yellow-500 text-gray-900 rounded-full flex items-center justify-center font-bold text-lg mb-4">
                  {step.number}
                </div>
                <h3 className="text-xl font-bold text-gray-900 mb-3">{step.title}</h3>
                <p className="text-gray-600 leading-relaxed">{step.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function ImpactStats() {
  const metrics = [
    {
      number: '500+',
      label: 'Institutions Partnering',
      subtext: 'Universities worldwide trust edu.cloud',
    },
    {
      number: '2.5M+',
      label: 'Alumni Tracked',
      subtext: 'Professional outcomes analyzed',
    },
    {
      number: '45K+',
      label: 'Companies Founded',
      subtext: 'Startups launched by alumni',
    },
    {
      number: '250K+',
      label: 'Jobs Created',
      subtext: 'Employment generated',
    },
    {
      number: '$12B+',
      label: 'Capital Raised',
      subtext: 'Venture funding by alumni',
    },
    {
      number: '1,200+',
      label: 'Exit Events',
      subtext: 'IPOs, acquisitions, mergers',
    },
  ];

  return (
    <section className="py-20 px-4 sm:px-6 lg:px-8 bg-white">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-gray-900 mb-4">
            Real Results at Scale
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Proven metrics from institutions measuring alumni impact with edu.cloud.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {metrics.map((metric, index) => (
            <div
              key={index}
              className="bg-gradient-to-br from-yellow-50 to-amber-50 rounded-xl p-8 text-center border border-yellow-200"
            >
              <div className="text-4xl sm:text-5xl font-bold text-yellow-600 mb-2">
                {metric.number}
              </div>
              <h3 className="text-lg font-bold text-gray-900 mb-2">{metric.label}</h3>
              <p className="text-sm text-gray-600">{metric.subtext}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function WhyChooseUs() {
  const reasons = [
    {
      title: 'Comprehensive Research',
      description: 'We go beyond LinkedIn to identify all significant alumni achievements across online sources.',
    },
    {
      title: 'Data-Driven Storytelling',
      description: 'Transform raw metrics into compelling narratives that resonate with donors and stakeholders.',
    },
    {
      title: 'Scalable Solutions',
      description: 'Handle portfolios from hundreds to millions of alumni efficiently and accurately.',
    },
    {
      title: 'Enterprise Security',
      description: 'GDPR and FERPA compliant with enterprise-grade security for sensitive educational data.',
    },
  ];

  return (
    <section className="py-20 px-4 sm:px-6 lg:px-8 bg-yellow-50">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-gray-900 mb-4">
            Why Choose edu.cloud
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Leading institutions depend on us to demonstrate their real impact.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {reasons.map((reason, index) => (
            <div key={index} className="bg-white rounded-xl p-8 border border-yellow-200">
              <h3 className="text-xl font-bold text-gray-900 mb-3">{reason.title}</h3>
              <p className="text-gray-600 leading-relaxed">{reason.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

export default function Home() {
  return (
    <main className="min-h-screen bg-white">
      <Header />
      <Hero />
      <Features />
      <Process />
      <ImpactStats />
      <WhyChooseUs />
      <CTA />
      <Footer />
    </main>
  );
}